module.exports = [
  {
    "login": "Aweary",
    "id": 6886061,
    "avatar_url": null,
    "gravatar_id": "",
    "url": "https://api.github.com/users/Aweary",
    "html_url": 1000,
    "followers_url": "https://api.github.com/users/Aweary/followers",
    "following_url": "https://api.github.com/users/Aweary/following{/other_user}",
    "gists_url": "https://api.github.com/users/Aweary/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Aweary/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Aweary/subscriptions",
    "organizations_url": "https://api.github.com/users/Aweary/orgs",
    "repos_url": "https://api.github.com/users/Aweary/repos",
    "events_url": "https://api.github.com/users/Aweary/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Aweary/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Brandon Dail",
    "company": "Concierge Auctions",
    "blog": "brandondail.me",
    "location": "United States",
    "email": "cottoncrypt@gmail.com",
    "hireable": true,
    "bio": "Developer at @ConciergeAuctions, enzyme mainter, stateless and pure.",
    "public_repos": 90,
    "public_gists": 21,
    "followers": 44,
    "following": 141,
    "created_at": "2014-03-07T18:19:20Z",
    "updated_at": "2016-06-07T20:22:00Z"
  },
  {
    "login": "Aweary",
    "id": 6886061,
    "avatar_url": "https://avatars.githubusercontent.com/u/6886061?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Aweary",
    "html_url": "https://github.com/Aweary",
    "followers_url": "https://api.github.com/users/Aweary/followers",
    "following_url": "https://api.github.com/users/Aweary/following{/other_user}",
    "gists_url": "https://api.github.com/users/Aweary/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Aweary/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Aweary/subscriptions",
    "organizations_url": "https://api.github.com/users/Aweary/orgs",
    "repos_url": "https://api.github.com/users/Aweary/repos",
    "events_url": "https://api.github.com/users/Aweary/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Aweary/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Brandon Dail",
    "company": "Concierge Auctions",
    "blog": "brandondail.me",
    "location": "United States",
    "email": "cottoncrypt@gmail.com",
    "hireable": true,
    "bio": "Developer at @ConciergeAuctions, enzyme mainter, stateless and pure.",
    "public_repos": 90,
    "public_gists": 21,
    "followers": 44,
    "following": 141,
    "created_at": "2014-03-07T18:19:20Z",
    "updated_at": "2016-06-07T20:22:00Z"
  }

]
